version: '3.3'  # or any other version that suits your needs

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8845:80"  # Map port 8080 on the host to port 80 in the container
    restart: always
