version: '3.3'

services:
  angular-app:
    build: .
    ports:
      - "4900:80"  # Maps host port 4800 to container port 80
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development  # Make sure to use the correct environment if needed
    restart: always
