apiVersion: v1
kind: Service
metadata:
  name: angular-k8s-demo-service
spec:
  selector:
    app: angular-k8s-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
