
const countries = [
        {
          name: 'Afghanistan',
          shortName: 'AFG',
          code:"+93",
          states: [
            {
              name: 'Kabul',
              cities: ['Kabul', 'Paghman', 'Charikar']
            },
            {
              name: 'Kandahar',
              cities: ['Kandahar City', 'Spin Boldak']
            },
            {
              name: 'Herat',
              cities: ['Herat City', 'Islam Qala']
            },
            {
              name: 'Balkh',
              cities: ['Mazar-i-Sharif', 'Balkh City']
            },
            {
              name: 'Nangarhar',
              cities: ['Jalalabad', 'Behsud']
            },
            {
              name: 'Badakhshan',
              cities: ['Fayzabad', 'Jurm']
            },
            {
              name: 'Baghlan',
              cities: ['Pul-e-Khumri', 'Baghlan City']
            },
            {
              name: 'Ghazni',
              cities: ['Ghazni City', 'Qarabagh']
            },
            {
              name: 'Faryab',
              cities: ['Maymana', 'Andkhoy']
            },
            {
              name: 'Helmand',
              cities: ['Lashkar Gah', 'Sangin']
            }
          ]
        },
      
    { name: 'United States', code: '+1', shortName: 'USA', states: [
        { state: 'Alabama', abbreviation: 'AL', cities: ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile', 'Tuscaloosa'] },
        { state: 'Alaska', abbreviation: 'AK', cities: ['Anchorage', 'Fairbanks', 'Juneau', 'Sitka', 'Ketchikan'] },
        { state: 'Arizona', abbreviation: 'AZ', cities: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale'] },
        { state: 'Arkansas', abbreviation: 'AR', cities: ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro'] },
        { state: 'California', abbreviation: 'CA', cities: ['Los Angeles', 'San Francisco', 'San Diego', 'San Jose', 'Sacramento'] },
        { state: 'Colorado', abbreviation: 'CO', cities: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood'] },
        { state: 'Connecticut', abbreviation: 'CT', cities: ['Hartford', 'Bridgeport', 'New Haven', 'Stamford', 'Waterbury'] },
        { state: 'Delaware', abbreviation: 'DE', cities: ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Smyrna'] },
        { state: 'Florida', abbreviation: 'FL', cities: ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg'] },
        { state: 'Georgia', abbreviation: 'GA', cities: ['Atlanta', 'Augusta', 'Columbus', 'Savannah', 'Macon'] },
        { state: 'Hawaii', abbreviation: 'HI', cities: ['Honolulu', 'Hilo', 'Kailua', 'Kaneohe', 'Lahaina'] },
        { state: 'Idaho', abbreviation: 'ID', cities: ['Boise', 'Nampa', 'Meridian', 'Idaho Falls', 'Pocatello'] },
        { state: 'Illinois', abbreviation: 'IL', cities: ['Chicago', 'Aurora', 'Naperville', 'Rockford', 'Joliet'] },
        { state: 'Indiana', abbreviation: 'IN', cities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel'] },
        { state: 'Iowa', abbreviation: 'IA', cities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City'] },
        { state: 'Kansas', abbreviation: 'KS', cities: ['Wichita', 'Overland Park', 'Kansas City', 'Topeka', 'Olathe'] },
        { state: 'Kentucky', abbreviation: 'KY', cities: ['Louisville', 'Lexington', 'Bowling Green', 'Covington', 'Richmond'] },
        { state: 'Louisiana', abbreviation: 'LA', cities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'] },
        { state: 'Maine', abbreviation: 'ME', cities: ['Portland', 'Augusta', 'Bangor', 'South Portland', 'Auburn'] },
        { state: 'Maryland', abbreviation: 'MD', cities: ['Baltimore', 'Frederick', 'Rockville', 'Gaithersburg', 'Bowie'] },
        { state: 'Massachusetts', abbreviation: 'MA', cities: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'] },
        { state: 'Michigan', abbreviation: 'MI', cities: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor'] },
        { state: 'Minnesota', abbreviation: 'MN', cities: ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington'] },
        { state: 'Mississippi', abbreviation: 'MS', cities: ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi'] },
        { state: 'Missouri', abbreviation: 'MO', cities: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Independence'] },
        { state: 'Montana', abbreviation: 'MT', cities: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Butte'] },
        { state: 'Nebraska', abbreviation: 'NE', cities: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney'] },
        { state: 'Nevada', abbreviation: 'NV', cities: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks'] },
        { state: 'New Hampshire', abbreviation: 'NH', cities: ['Manchester', 'Nashua', 'Concord', 'Derry', 'Rochester'] },
        { state: 'New Jersey', abbreviation: 'NJ', cities: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison'] },
        { state: 'New Mexico', abbreviation: 'NM', cities: ['Albuquerque', 'Las Cruces', 'Santa Fe', 'Roswell', 'Farmington'] },
        { state: 'New York', abbreviation: 'NY', cities: ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse'] },
        { state: 'North Carolina', abbreviation: 'NC', cities: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'] },
        { state: 'North Dakota', abbreviation: 'ND', cities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo'] },
        { state: 'Ohio', abbreviation: 'OH', cities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'] },
        { state: 'Oklahoma', abbreviation: 'OK', cities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'] },
        { state: 'Oregon', abbreviation: 'OR', cities: ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro'] },
        { state: 'Pennsylvania', abbreviation: 'PA', cities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading'] },
        { state: 'Rhode Island', abbreviation: 'RI', cities: ['Providence', 'Warwick', 'Cranston', 'Pawtucket', 'East Providence'] },
        { state: 'South Carolina', abbreviation: 'SC', cities: ['Columbia', 'Charleston', 'North Charleston', 'Mount Pleasant', 'Rock Hill'] },
        { state: 'South Dakota', abbreviation: 'SD', cities: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Mitchell'] },
        { state: 'Tennessee', abbreviation: 'TN', cities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'] },
        { state: 'Texas', abbreviation: 'TX', cities: ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth'] },
        { state: 'Utah', abbreviation: 'UT', cities: ['Salt Lake City', 'West Valley City', 'Provo', 'Sandy', 'Orem'] },
        { state: 'Vermont', abbreviation: 'VT', cities: ['Burlington', 'Essex', 'South Burlington', 'Rutland', 'Barre'] },
        { state: 'Virginia', abbreviation: 'VA', cities: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Newport News'] },
        { state: 'Washington', abbreviation: 'WA', cities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'] },
        { state: 'West Virginia', abbreviation: 'WV', cities: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Weirton'] },
        { state: 'Wisconsin', abbreviation: 'WI', cities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'] },
        { state: 'Wyoming', abbreviation: 'WY', cities: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs'] },
      ]
           },
    { name: 'United Kingdom', code: '+44', shortName: 'UK',states: [
        { state: 'England', abbreviation: 'ENG', cities: ['London', 'Birmingham', 'Manchester', 'Liverpool', 'Bristol'] },
        { state: 'Scotland', abbreviation: 'SCT', cities: ['Edinburgh', 'Glasgow', 'Aberdeen', 'Dundee', 'Inverness'] },
        { state: 'Wales', abbreviation: 'WLS', cities: ['Cardiff', 'Swansea', 'Newport', 'Wrexham', 'Barry'] },
        { state: 'Northern Ireland', abbreviation: 'NIR', cities: ['Belfast', 'Derry', 'Lisburn', 'Newtownabbey', 'Carrickfergus'] },
      ]
     },
    { name: 'India', code: '+91', shortName: 'IND', states: [
        { state: 'Andhra Pradesh', abbreviation: 'AP', cities: ['Hyderabad', 'Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore'] },
        { state: 'Arunachal Pradesh', abbreviation: 'AR', cities: ['Itanagar', 'Naharlagun', 'Pasighat', 'Tezpur', 'Bomdila'] },
        { state: 'Assam', abbreviation: 'AS', cities: ['Guwahati', 'Dispur', 'Dibrugarh', 'Silchar', 'Nagaon'] },
        { state: 'Bihar', abbreviation: 'BR', cities: ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Darbhanga'] },
        { state: 'Chhattisgarh', abbreviation: 'CG', cities: ['Raipur', 'Bilaspur', 'Durg', 'Bhilai', 'Korba'] },
        { state: 'Goa', abbreviation: 'GA', cities: ['Panaji', 'Margao', 'Vasco da Gama', 'Ponda', 'Mapusa'] },
        { state: 'Gujarat', abbreviation: 'GJ', cities: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Gandhinagar'] },
        { state: 'Haryana', abbreviation: 'HR', cities: ['Chandigarh', 'Gurgaon', 'Faridabad', 'Hisar', 'Panipat'] },
        { state: 'Himachal Pradesh', abbreviation: 'HP', cities: ['Shimla', 'Dharamshala', 'Kullu', 'Manali', 'Solan'] },
        { state: 'Jharkhand', abbreviation: 'JH', cities: ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar'] },
        { state: 'Karnataka', abbreviation: 'KA', cities: ['Bengaluru', 'Mysuru', 'Mangaluru', 'Hubli', 'Davangere'] },
        { state: 'Kerala', abbreviation: 'KL', cities: ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Kollam', 'Malappuram'] },
        { state: 'Madhya Pradesh', abbreviation: 'MP', cities: ['Bhopal', 'Indore', 'Gwalior', 'Jabalpur', 'Ujjain'] },
        { state: 'Maharashtra', abbreviation: 'MH', cities: ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Aurangabad'] },
        { state: 'Manipur', abbreviation: 'MN', cities: ['Imphal', 'Thoubal', 'Kakching', 'Churachandpur', 'Tamenglong'] },
        { state: 'Meghalaya', abbreviation: 'ML', cities: ['Shillong', 'Tura', 'Jowai', 'Nongpoh', 'Bholaganj'] },
        { state: 'Mizoram', abbreviation: 'MZ', cities: ['Aizawl', 'Lunglei', 'Saiha', 'Kolasib', 'Mamit'] },
        { state: 'Nagaland', abbreviation: 'NL', cities: ['Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha'] },
        { state: 'Odisha', abbreviation: 'OR', cities: ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur', 'Sambalpur'] },
        { state: 'Punjab', abbreviation: 'PB', cities: ['Chandigarh', 'Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala'] },
        { state: 'Rajasthan', abbreviation: 'RJ', cities: ['Jaipur', 'Udaipur', 'Jodhpur', 'Ajmer', 'Bikaner'] },
        { state: 'Sikkim', abbreviation: 'SK', cities: ['Gangtok', 'Namchi', 'Mangan', 'Gyalshing', 'Pakyong'] },
        { state: 'Tamil Nadu', abbreviation: 'TN', cities: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem'] },
        { state: 'Telangana', abbreviation: 'TG', cities: ['Hyderabad', 'Warangal', 'Nizamabad', 'Khammam', 'Karimnagar'] },
        { state: 'Tripura', abbreviation: 'TR', cities: ['Agartala', 'Ambassa', 'Udaipur', 'Dharmanagar', 'Belonia'] },
        { state: 'Uttar Pradesh', abbreviation: 'UP', cities: ['Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Meerut'] },
        { state: 'Uttarakhand', abbreviation: 'UK', cities: ['Dehradun', 'Haridwar', 'Nainital', 'Rudrapur', 'Roorkee'] },
        { state: 'West Bengal', abbreviation: 'WB', cities: ['Kolkata', 'Siliguri', 'Asansol', 'Durgapur', 'Howrah'] },
      ] },
    { name: 'Australia', code: '+61', shortName: 'AUS',  states: [
        { state: 'New South Wales', abbreviation: 'NSW', cities: ['Sydney', 'Newcastle', 'Wollongong', 'Central Coast', 'Coffs Harbour'] },
        { state: 'Victoria', abbreviation: 'VIC', cities: ['Melbourne', 'Geelong', 'Ballarat', 'Bendigo', 'Mildura'] },
        { state: 'Queensland', abbreviation: 'QLD', cities: ['Brisbane', 'Gold Coast', 'Cairns', 'Townsville', 'Mackay'] },
        { state: 'Western Australia', abbreviation: 'WA', cities: ['Perth', 'Bunbury', 'Mandurah', 'Geraldton', 'Kalgoorlie'] },
        { state: 'South Australia', abbreviation: 'SA', cities: ['Adelaide', 'Mount Gambier', 'Whyalla', 'Murray Bridge', 'Port Augusta'] },
        { state: 'Tasmania', abbreviation: 'TAS', cities: ['Hobart', 'Launceston', 'Devonport', 'Burnie', 'Kingston'] },
        { state: 'Australian Capital Territory', abbreviation: 'ACT', cities: ['Canberra', 'Queanbeyan', 'Gungahlin', 'Tuggeranong', 'Belconnen'] },
        { state: 'Northern Territory', abbreviation: 'NT', cities: ['Darwin', 'Alice Springs', 'Katherine', 'Casuarina', 'Palmerston'] },      
    ] },
        { name: 'Japan', code: '+81', shortName: 'JPN', states: [{ state: 'Tokyo', cities: ['Tokyo', 'Shinjuku', 'Shibuya', 'Ikebukuro'] }] },
        { name: 'Germany', code: '+49', shortName: 'DEU', states: [{ state: 'Bavaria', cities: ['Munich', 'Nuremberg', 'Augsburg', 'Regensburg'] }] },
        { name: 'Canada', code: '+1', shortName: 'CAN', states: [{ state: 'Ontario', cities: ['Toronto', 'Ottawa', 'Mississauga', 'Brampton'] }] },
        { name: 'France', code: '+33', shortName: 'FRA', states: [{ state: 'Île-de-France', cities: ['Paris', 'Versailles', 'Boulogne-Billancourt', 'Saint-Denis'] }] },
        { name: 'Brazil', code: '+55', shortName: 'BRA', states: [{ state: 'São Paulo', cities: ['São Paulo', 'Campinas', 'Santo André', 'Osasco'] }] },
        { name: 'Mexico', code: '+52', shortName: 'MEX', states: [{ state: 'Mexico City', cities: ['Mexico City', 'Ecatepec', 'Nezahualcóyotl', 'Tlalnepantla'] }] },
        { name: 'Italy', code: '+39', shortName: 'ITA', states: [{ state: 'Lazio', cities: ['Rome', 'Fiumicino', 'Tivoli', 'Civitavecchia'] }] },
        { name: 'Russia', code: '+7', shortName: 'RUS', states: [{ state: 'Moscow', cities: ['Moscow', 'Zelenograd', 'Podolsk', 'Khimki'] }] },
        { name: 'South Africa', code: '+27', shortName: 'ZAF', states: [{ state: 'Gauteng', cities: ['Johannesburg', 'Pretoria', 'Soweto', 'Ekurhuleni'] }] },
        { name: 'Netherlands', code: '+31', shortName: 'NLD', states: [{ state: 'North Holland', cities: ['Amsterdam', 'Haarlem', 'Hilversum', 'Alkmaar'] }] },
        { name: 'Spain', code: '+34', shortName: 'ESP', states: [{ state: 'Madrid', cities: ['Madrid', 'Alcalá de Henares', 'Móstoles', 'Getafe'] }] },
        { name: 'Turkey', code: '+90', shortName: 'TUR', states: [{ state: 'Istanbul', cities: ['Istanbul', 'Kadıköy', 'Beyoğlu', 'Şişli'] }] },
        { name: 'New Zealand', code: '+64', shortName: 'NZL', states: [{ state: 'Auckland', cities: ['Auckland', 'Hamilton', 'Tauranga', 'Dunedin'] }] },
        { name: 'Sweden', code: '+46', shortName: 'SWE', states: [{ state: 'Stockholm', cities: ['Stockholm', 'Uppsala', 'Sundbyberg', 'Södertälje'] }] },
        { name: 'Norway', code: '+47', shortName: 'NOR', states: [{ state: 'Oslo', cities: ['Oslo', 'Drammen', 'Bergen', 'Stavanger'] }] },
        { name: 'Argentina', code: '+54', shortName: 'ARG', states: [{ state: 'Buenos Aires', cities: ['Buenos Aires', 'La Plata', 'Mar del Plata', 'Rosario'] }] },
        { name: 'Chile', code: '+56', shortName: 'CHL', states: [{ state: 'Santiago Metropolitan', cities: ['Santiago', 'Puente Alto', 'Maipú', 'Las Condes'] }] },
        { name: 'Singapore', code: '+65', shortName: 'SGP', states: [{ state: 'Central Region', cities: ['Singapore', 'Jurong', 'Yishun', 'Bukit Batok'] }] },
        { name: 'Philippines', code: '+63', shortName: 'PHL', states: [{ state: 'Metro Manila', cities: ['Manila', 'Quezon City', 'Caloocan', 'Pasig'] }] },
        { name: 'Indonesia', code: '+62', shortName: 'IDN', states: [{ state: 'Bali', cities: ['Denpasar', 'Ubud', 'Kuta', 'Seminyak'] }] },
        { name: 'Thailand', code: '+66', shortName: 'THA', states: [{ state: 'Bangkok', cities: ['Bangkok', 'Nonthaburi', 'Samut Prakan', 'Nakhon Pathom'] }] },
        { name: 'Vietnam', code: '+84', shortName: 'VNM', states: [{ state: 'Hanoi', cities: ['Hanoi', 'Ho Chi Minh City', 'Hai Phong', 'Da Nang'] }] },
        { name: 'Pakistan', code: '+92', shortName: 'PAK', states: [{ state: 'Punjab', cities: ['Lahore', 'Faisalabad', 'Rawalpindi', 'Multan'] }] },
        { name: 'Bangladesh', code: '+880', shortName: 'BGD', states: [{ state: 'Dhaka', cities: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi'] }] },
        { name: 'Nigeria', code: '+234', shortName: 'NGA', states: [{ state: 'Lagos', cities: ['Lagos', 'Ikeja', 'Victoria Island', 'Badagry'] }] },
        { name: 'Egypt', code: '+20', shortName: 'EGY', states: [{ state: 'Cairo', cities: ['Cairo', 'Giza', 'Alexandria', 'Shubra El Kheima'] }] },
        { name: 'Saudi Arabia', code: '+966', shortName: 'SAU', states: [{ state: 'Riyadh', cities: ['Riyadh', 'Jeddah', 'Dammam', 'Khobar'] }] },
        { name: 'United Arab Emirates', code: '+971', shortName: 'ARE', states: [{ state: 'Dubai', cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman'] }] },
        { name: 'Israel', code: '+972', shortName: 'ISR', states: [{ state: 'Tel Aviv', cities: ['Tel Aviv', 'Jerusalem', 'Haifa', 'Rishon Lezion'] }] },
        { name: 'Malaysia', code: '+60', shortName: 'MYS', states: [{ state: 'Selangor', cities: ['Shah Alam', 'Subang Jaya', 'Petaling Jaya', 'Klang'] }] },
        { name: 'Ireland', code: '+353', shortName: 'IRL', states: [{ state: 'Leinster', cities: ['Dublin', 'Cork', 'Limerick', 'Waterford'] }] },
        { name: 'Czech Republic', code: '+420', shortName: 'CZE', states: [{ state: 'Prague', cities: ['Prague', 'Brno', 'Ostrava', 'Plzeň'] }] },
        { name: 'Greece', code: '+30', shortName: 'GRC', states: [{ state: 'Attica', cities: ['Athens', 'Piraeus', 'Kallithea', 'Peristeri'] }] },
        { name: 'Finland', code: '+358', shortName: 'FIN', states: [{ state: 'Uusimaa', cities: ['Helsinki', 'Espoo', 'Vantaa', 'Kauniainen'] }] },
        { name: 'Hungary', code: '+36', shortName: 'HUN', states: [{ state: 'Budapest', cities: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc'] }] },
        { name: 'Iceland', code: '+354', shortName: 'ISL', states: [{ state: 'Reykjavík', cities: ['Reykjavík', 'Kopavogur', 'Hafnarfjordur', 'Akureyri'] }] },
        { name: 'Portugal', code: '+351', shortName: 'PRT', states: [{ state: 'Lisbon', cities: ['Lisbon', 'Porto', 'Amadora', 'Braga'] }] },
        { name: 'Estonia', code: '+372', shortName: 'EST', states: [{ state: 'Tallinn', cities: ['Tallinn', 'Tartu', 'Narva', 'Kohtla-Järve'] }] },
        { name: 'Latvia', code: '+371', shortName: 'LVA', states: [{ state: 'Riga', cities: ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava'] }] },
        { name: 'Lithuania', code: '+370', shortName: 'LTU', states: [{ state: 'Vilnius', cities: ['Vilnius', 'Kaunas', 'Klaipeda', 'Šiauliai'] }] },
        { name: 'Slovakia', code: '+421', shortName: 'SVK', states: [{ state: 'Bratislava', cities: ['Bratislava', 'Košice', 'Nitra', 'Prešov'] }] },
        { name: 'Slovenia', code: '+386', shortName: 'SVN', states: [{ state: 'Ljubljana', cities: ['Ljubljana', 'Maribor', 'Celje', 'Kranj'] }] },
        { name: 'Serbia', code: '+381', shortName: 'SRB', states: [{ state: 'Belgrade', cities: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac'] }] },
        { name: 'Croatia', code: '+385', shortName: 'HRV', states: [{ state: 'Zagreb', cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek'] }] },
        { name: 'Bosnia and Herzegovina', code: '+387', shortName: 'BIH', states: [{ state: 'Federation of Bosnia and Herzegovina', cities: ['Sarajevo', 'Zenica', 'Tuzla', 'Mostar'] }] },
        { name: 'Montenegro', code: '+382', shortName: 'MNE', states: [{ state: 'Podgorica', cities: ['Podgorica', 'Nikšić', 'Herceg Novi', 'Bijelo Polje'] }] },
        { name: 'North Macedonia', code: '+389', shortName: 'MKD', states: [{ state: 'Skopje', cities: ['Skopje', 'Bitola', 'Kumanovo', 'Tetovo'] }] },
        { name: 'Albania', code: '+355', shortName: 'ALB', states: [{ state: 'Tirana', cities: ['Tirana', 'Durrës', 'Vlorë', 'Fier'] }] },
        { name: 'Moldova', code: '+373', shortName: 'MDA', states: [{ state: 'Chișinău', cities: ['Chișinău', 'Bălți', 'Bender', 'Rîbnița'] }] },
        { name: 'Armenia', code: '+374', shortName: 'ARM', states: [{ state: 'Yerevan', cities: ['Yerevan', 'Gyumri', 'Vagharshapat', 'Vanadzor'] }] },
        { name: 'Georgia', code: '+995', shortName: 'GEO', states: [{ state: 'Tbilisi', cities: ['Tbilisi', 'Kutaisi', 'Zugdidi', 'Batumi'] }] },
        { name: 'Kazakhstan', code: '+7', shortName: 'KAZ', states: [{ state: 'Almaty', cities: ['Almaty', 'Astana', 'Shymkent', 'Karaganda'] }] },
        { name: 'Uzbekistan', code: '+998', shortName: 'UZB', states: [{ state: 'Tashkent', cities: ['Tashkent', 'Samarkand', 'Bukhara', 'Andijan'] }] },
        { name: 'Kyrgyzstan', code: '+996', shortName: 'KGZ', states: [{ state: 'Bishkek', cities: ['Bishkek', 'Osh', 'Jalal-Abad', 'Tokmok'] }] },
        { name: 'Tajikistan', code: '+992', shortName: 'TJK', states: [{ state: 'Dushanbe', cities: ['Dushanbe', 'Khujand', 'Kulob', 'Istaravshan'] }] },
        { name: 'Turkmenistan', code: '+993', shortName: 'TKM', states: [{ state: 'Ashgabat', cities: ['Ashgabat', 'Turkmenbashi', 'Mary', 'Balkanabat'] }] },
        { name: 'Qatar', code: '+974', shortName: 'QAT', states: [{ state: 'Doha', cities: ['Doha', 'Al Rayyan', 'Al Wakrah', 'Umm Salal'] }] },
        { name: 'Oman', code: '+968', shortName: 'OMN', states: [{ state: 'Muscat', cities: ['Muscat', 'Salalah', 'Sohar', 'Nizwa'] }] },
        { name: 'Bahrain', code: '+973', shortName: 'BHR', states: [{ state: 'Manama', cities: ['Manama', 'Muharraq', 'Riffa', 'Sitra'] }] },
        { name: 'Kuwait', code: '+965', shortName: 'KWT', states: [{ state: 'Kuwait City', cities: ['Kuwait City', 'Al Ahmadi', 'Hawalli', 'Salmiya'] }] },
        { name: 'Lebanon', code: '+961', shortName: 'LBN', states: [{ state: 'Beirut', cities: ['Beirut', 'Tripoli', 'Sidon', 'Tyre'] }] },
        { name: 'Syria', code: '+963', shortName: 'SYR', states: [{ state: 'Damascus', cities: ['Damascus', 'Aleppo', 'Homs', 'Latakia'] }] },
        { name: 'Jordan', code: '+962', shortName: 'JOR', states: [{ state: 'Amman', cities: ['Amman', 'Zarqa', 'Irbid', 'Ajloun'] }] },
        { name: 'Yemen', code: '+967', shortName: 'YEM', states: [{ state: 'Sana\'a', cities: ['Sana\'a', 'Aden', 'Taiz', 'Hodeida'] }] },
        { name: 'Bhutan', code: '+975', shortName: 'BTN', states: [{ state: 'Thimphu', cities: ['Thimphu', 'Paro', 'Punakha', 'Wangdue Phodrang'] }] },
        { name: 'Maldives', code: '+960', shortName: 'MDV', states: [{ state: 'Malé', cities: ['Malé', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi'] }] },
        { name: 'Brunei', code: '+673', shortName: 'BRN', states: [{ state: 'Bandar Seri Begawan', cities: ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong'] }] },
        { name: 'Myanmar', code: '+95', shortName: 'MMR', states: [{ state: 'Yangon', cities: ['Yangon', 'Mandalay', 'Naypyidaw', 'Bago'] }] },
        { name: 'Cambodia', code: '+855', shortName: 'KHM', states: [{ state: 'Phnom Penh', cities: ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'] }] },
        { name: 'Laos', code: '+856', shortName: 'LAO', states: [{ state: 'Vientiane', cities: ['Vientiane', 'Luang Prabang', 'Savannakhet', 'Pakse'] }] },
        { name: 'Mongolia', code: '+976', shortName: 'MNG', states: [{ state: 'Ulaanbaatar', cities: ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Mörön'] }] },
        { name: 'Nepal', code: '+977', shortName: 'NPL', states: [{ state: 'Kathmandu', cities: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bhaktapur'] }] },
        { name: 'Sri Lanka', code: '+94', shortName: 'LKA', states: [{ state: 'Western', cities: ['Colombo', 'Galle', 'Kandy', 'Negombo'] }] },
        { name: 'Somalia', code: '+252', shortName: 'SOM', states: [{ state: 'Mogadishu', cities: ['Mogadishu', 'Hargeisa', 'Kismayo', 'Baidoa'] }] },
        { name: 'Sudan', code: '+249', shortName: 'SDN', states: [{ state: 'Khartoum', cities: ['Khartoum', 'Omdurman', 'Port Sudan', 'El Obeid'] }] },
        { name: 'Zimbabwe', code: '+263', shortName: 'ZWE', states: [{ state: 'Harare', cities: ['Harare', 'Bulawayo', 'Gweru', 'Kwekwe'] }] },
        { name: 'Kenya', code: '+254', shortName: 'KEN', states: [{ state: 'Nairobi', cities: ['Nairobi', 'Mombasa', 'Nakuru', 'Eldoret'] }] },
        { name: 'Uganda', code: '+256', shortName: 'UGA', states: [{ state: 'Kampala', cities: ['Kampala', 'Entebbe', 'Mbarara', 'Jinja'] }] },
        { name: 'Tanzania', code: '+255', shortName: 'TZA', states: [{ state: 'Dodoma', cities: ['Dodoma', 'Dar es Salaam', 'Arusha', 'Mbeya'] }] },
        { name: 'Rwanda', code: '+250', shortName: 'RWA', states: [{ state: 'Kigali', cities: ['Kigali', 'Butare', 'Gisenyi', 'Musanze'] }] },
        { name: 'Ghana', code: '+233', shortName: 'GHA', states: [{ state: 'Accra', cities: ['Accra', 'Kumasi', 'Tamale', 'Takoradi'] }] },
        { name: 'Angola', code: '+244', shortName: 'AGO', states: [{ state: 'Luanda', cities: ['Luanda', "N'dalatando", 'Huambo', 'Lubango'] }] },
        { name: 'Zambia', code: '+260', shortName: 'ZMB', states: [{ state: 'Lusaka', cities: ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe'] }] },
        { name: 'Botswana', code: '+267', shortName: 'BWA', states: [{ state: 'Gaborone', cities: ['Gaborone', 'Francistown', 'Maun', 'Kasane'] }] },
        { name: 'Namibia', code: '+264', shortName: 'NAM', states: [{ state: 'Windhoek', cities: ['Windhoek', 'Swakopmund', 'Walvis Bay', 'Oshakati'] }] },
        { name: 'Lesotho', code: '+266', shortName: 'LSO', states: [{ state: 'Maseru', cities: ['Maseru', 'Teyateyaneng', 'Maputsoe', 'Quthing'] }] },
        { name: 'Swaziland', code: '+268', shortName: 'SWZ', states: [{ state: 'Mbabane', cities: ['Mbabane', 'Manzini', 'Siteki', 'Piggs Peak'] }] },
        { name: 'Malawi', code: '+265', shortName: 'MWI', states: [{ state: 'Lilongwe', cities: ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'] }] },
        { name: 'Sierra Leone', code: '+232', shortName: 'SLE', states: [{ state: 'Freetown', cities: ['Freetown', 'Bo', 'Kenema', 'Makeni'] }] },
        { name: 'Liberia', code: '+231', shortName: 'LBR', states: [{ state: 'Monrovia', cities: ['Monrovia', 'Gbarnga', 'Kakata', 'Bong'] }] },
        { name: 'Togo', code: '+228', shortName: 'TGO', states: [{ state: 'Lomé', cities: ['Lomé', 'Sokodé', 'Kpalimé', 'Atakpamé'] }] },
        { name: 'Ivory Coast', code: '+225', shortName: 'CIV', states: [{ state: 'Yamoussoukro', cities: ['Yamoussoukro', 'Abidjan', 'Bouaké', 'San Pedro'] }] },
        { name: 'Senegal', code: '+221', shortName: 'SEN', states: [{ state: 'Dakar', cities: ['Dakar', 'Touba', 'Thiès', 'Saint-Louis'] }] },
        { name: 'Cameroon', code: '+237', shortName: 'CMR', states: [{ state: 'Yaoundé', cities: ['Yaoundé', 'Douala', 'Garoua', 'Bafoussam'] }] },
        { name: 'Chad', code: '+235', shortName: 'TCD', states: [{ state: "N'Djamena", cities: ["N'Djamena", 'Moundou', 'Sarh', 'Abéché'] }] },
        { name: 'Central African Republic', code: '+236', shortName: 'CAF', states: [{ state: 'Bangui', cities: ['Bangui', 'Berberati', 'Bimbo', 'Mbaïki'] }] },
        { name: 'Republic of the Congo', code: '+242', shortName: 'COG', states: [{ state: 'Brazzaville', cities: ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Oyo'] }] },
        { name: 'Democratic Republic of the Congo', code: '+243', shortName: 'COD', states: [{ state: 'Kinshasa', cities: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani'] }] },
        { name: 'Gabon', code: '+241', shortName: 'GAB', states: [{ state: 'Libreville', cities: ['Libreville', 'Port-Gentil', 'Franceville', 'Moanda'] }] },
        { name: 'Equatorial Guinea', code: '+240', shortName: 'GNQ', states: [{ state: 'Malabo', cities: ['Malabo', 'Bata', 'Ebebiyin', 'Aconibe'] }] },
        { name: 'Mauritius', code: '+230', shortName: 'MUS', states: [{ state: 'Port Louis', cities: ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix', 'Curepipe'] }] },
        { name: 'Mali', code: '+223', shortName: 'MLI', states: [{ state: 'Bamako', cities: ['Bamako', 'Sikasso', 'Kayes', 'Mopti'] }] },
        { name: 'Niger', code: '+227', shortName: 'NER', states: [{ state: 'Niamey', cities: ['Niamey', 'Zinder', 'Maradi', 'Agadez'] }] },
        { name: 'Burkina Faso', code: '+226', shortName: 'BFA', states: [{ state: 'Ouagadougou', cities: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora'] }] },
        { name: 'Burundi', code: '+257', shortName: 'BDI', states: [{ state: 'Gitega', cities: ['Gitega', 'Bujumbura', 'Ngozi', 'Cankuzo'] }] },
        { name: 'Djibouti', code: '+253', shortName: 'DJI', states: [{ state: 'Djibouti', cities: ['Djibouti', 'Ali Sabieh', 'Dikhil', 'Tadjourah'] }] },
        { name: 'Sao Tome and Principe', code: '+239', shortName: 'STP', states: [{ state: 'São Tomé', cities: ['São Tomé', 'Principe', 'Neves', 'Santa Catarina'] }] },
        { name: 'Gambia', code: '+220', shortName: 'GMB', states: [{ state: 'Banjul', cities: ['Banjul', 'Serrekunda', 'Brikama', 'Gunjur'] }] },
        { name: 'Comoros', code: '+269', shortName: 'COM', states: [{ state: 'Moroni', cities: ['Moroni', 'Moutsamoudou', 'Domoni', 'Fumbuni'] }] },
        { name: 'Seychelles', code: '+248', shortName: 'SYC', states: [{ state: 'Victoria', cities: ['Victoria', 'Beau Vallon', 'Anse Royale', 'Praslin'] }] },
        { name: 'Anguilla', code: '+1 264', shortName: 'AIA', states: [{ state: 'The Valley', cities: ['The Valley', 'East End', 'Blowing Point', 'Sandy Ground'] }] },
        { name: 'Antigua and Barbuda', code: '+1 268', shortName: 'ATG', states: [{ state: `Saint John's`, cities: ["Saint John's", 'All Saints', 'Liberta', 'Freetown'] }] },
        { name: 'Saint Kitts and Nevis', code: '+1 869', shortName: 'KNA', states: [{ state: 'Basseterre', cities: ['Basseterre', 'Clayton J. Lloyd International Airport'] }] },
        { name: 'Dominica', code: '+1 767', shortName: 'DMA', states: [{ state: 'Roseau', cities: ['Roseau', ' Portsmouth', 'Marigot', 'La Plaine'] }] },
        { name: 'Saint Lucia', code: '+1 758', shortName: 'LCA', states: [{ state: 'Castries', cities: ['Castries', 'Vieux Fort', 'Soufrière', 'Gros Islet'] }] },
        { name: 'Saint Vincent and the Grenadines', code: '+1 784', shortName: 'VCT', states: [{ state: 'Kingstown', cities: ['Kingstown', 'Villa', 'Barrouallie', 'Bequia'] }] },
        { name: 'Grenada', code: '+1 473', shortName: 'GRD', states: [{ state: 'Saint George\'s', cities: ['Saint George\'s', 'Gouyave', 'Victoria', 'Grenville'] }] },
        { name: 'Barbados', code: '+1 246', shortName: 'BRB', states: [{ state: 'Bridgetown', cities: ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba'] }] },
        { name: 'Bahamas', code: '+1 242', shortName: 'BHS', states: [{ state: 'Nassau', cities: ['Nassau', 'Freeport', 'West End', 'Marsh Harbour'] }] },
        { name: 'Cayman Islands', code: '+1 345', shortName: 'CYM', states: [{ state: 'George Town', cities: ['George Town', 'West Bay', 'Bodden Town', 'East End'] }] },
        { name: 'Turks and Caicos Islands', code: '+1 649', shortName: 'TCA', states: [{ state: 'Grand Turk', cities: ['Cockburn Town', 'Grand Turk', 'Salt Cay', 'South Caicos'] }] },
        { name: 'Jamaica', code: '+1 876', shortName: 'JAM', states: [{ state: 'Kingston', cities: ['Kingston', 'Montego Bay', 'Portmore', 'Spanish Town'] }] },
        { name: 'Puerto Rico', code: '+1 787', shortName: 'PRI', states: [{ state: 'San Juan', cities: ['San Juan', 'Bayamon', 'Ponce', 'Caguas'] }] },
        { name: 'Dominican Republic', code: '+1 809', shortName: 'DOM', states: [{ state: 'Santo Domingo', cities: ['Santo Domingo', 'Santiago de los Caballeros', 'La Romana', 'San Pedro de Macorís'] }] },
        { name: 'Haiti', code: '+509', shortName: 'HTI', states: [{ state: 'Port-au-Prince', cities: ['Port-au-Prince', 'Cap-Haïtien', 'Les Cayes', 'Pétion-Ville'] }] },
        { name: 'Cuba', code: '+53', shortName: 'CUB', states: [{ state: 'Havana', cities: ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín'] }] },
        { name: 'Nicaragua', code: '+505', shortName: 'NIC', states: [{ state: 'Managua', cities: ['Managua', 'León', 'Masaya', 'Granada'] }] },
        { name: 'Costa Rica', code: '+506', shortName: 'CRI', states: [{ state: 'San José', cities: ['San José', 'Alajuela', 'Cartago', 'Heredia'] }] },
        { name: 'Panama', code: '+507', shortName: 'PAN', states: [{ state: 'Panama City', cities: ['Panama City', 'Colón', 'David', 'Chitré'] }] },
        { name: 'El Salvador', code: '+503', shortName: 'SLV', states: [{ state: 'San Salvador', cities: ['San Salvador', 'Santa Ana', 'San Miguel', 'La Libertad'] }] },
        { name: 'Guatemala', code: '+502', shortName: 'GTM', states: [{ state: 'Guatemala City', cities: ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango'] }] },
        { name: 'Honduras', code: '+504', shortName: 'HND', states: [{ state: 'Tegucigalpa', cities: ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba'] }] },
        { name: 'Belize', code: '+501', shortName: 'BLZ', states: [{ state: 'Belmopan', cities: ['Belmopan', 'San Ignacio', 'Orange Walk', 'Corozal'] }] },
        { name: 'Barbados', code: '+1 246', shortName: 'BRB', states: [{ state: 'Bridgetown', cities: ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba'] }] }
  ];
  
  

export default countries
