name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ] # Replace with your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run:  npm install

      - name: Build Angular App
        run: npm run build --prod

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MANAGEMENT_45 }}'
          projectId: 'management-45'
          channelId: live # Or specify a different channel
